import { Inter } from "next/font/google";
import "./globals.css";
import "swiper/css";
import { Providers } from "./providers";
import MusicAppLayout from "@/components/shared/MusicAppLayout";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <Providers session={session}>
          <MusicAppLayout>{children}</MusicAppLayout>
        </Providers>
      </body>
    </html>
  );
}
